### ISSUE TITLE
shopware-deployment-helper run fails to upgrade

### ISSUE THREAD

**Issue by M-arcus** [shopware/deployment-helper#12]
```bash
vendor/bin/shopware-deployment-helper run --skip-assets-install --timeout=3600
```

```bash 
Shopware is installed, running update tools
Updating Shopware from unknown to 6.6.5.1
Fatal error: Uncaught TypeError: substr(): Argument #3 ($length) must be of type ?int, string given in vendor/symfony/process/PhpSubprocess.php:110
Stack trace:
#0 vendor/symfony/process/PhpSubprocess.php(110): substr()
#1 vendor/symfony/process/PhpSubprocess.php(66): Symfony\Component\Process\PhpSubprocess->writeTmpIni()
#2 vendor/shopware/deployment-helper/src/Helper/ProcessHelper.php(31): Symfony\Component\Process\PhpSubprocess->__construct()
#3 vendor/shopware/deployment-helper/src/Helper/ProcessHelper.php(60): Shopware\Deployment\Helper\ProcessHelper->run()
#4 vendor/shopware/deployment-helper/src/Services/UpgradeManager.php(41): Shopware\Deployment\Helper\ProcessHelper->console()
#5 vendor/shopware/deployment-helper/src/Command/RunCommand.php(53): Shopware\Deployment\Services\UpgradeManager->run()
#6 vendor/symfony/console/Command/Command.php(279): Shopware\Deployment\Command\RunCommand->execute()
#7 vendor/symfony/console/Application.php(1047): Symfony\Component\Console\Command\Command->run()
#8 vendor/symfony/console/Application.php(316): Symfony\Component\Console\Application->doRunCommand()
#9 vendor/symfony/console/Application.php(167): Symfony\Component\Console\Application->doRun()
#10 vendor/shopware/deployment-helper/bin/shopware-deployment-helper(31): Symfony\Component\Console\Application->run()
#11 vendor/bin/shopware-deployment-helper(119): include('...')
#12 {main}
  thrown in vendor/symfony/process/PhpSubprocess.php on line 110
```

**Comment by M-arcus** [comment]
https://github.com/symfony/symfony/pull/58195
